version: '2'

services:

  mongodb:
    image: 'mongo:3.6.7'
    ports:
      - '27017:27017'
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
      - MONGO_INITDB_DATABASE=shop_cms_db
    volumes:
      - './mongo/db:/data/db'
      - './mongo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'

#  mongo-express:
#    image: mongo-express
#    depends_on:
#      - mongodb
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
#      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass

